// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZqVMDCSXvTMTM216-3-YvqJDHR-qScM0',
    appId: '1:541360809178:web:59ed8c7e5c30ff93fa31e3',
    messagingSenderId: '541360809178',
    projectId: 'contact-app-6f595',
    authDomain: 'contact-app-6f595.firebaseapp.com',
    storageBucket: 'contact-app-6f595.appspot.com',
    measurementId: 'G-4SJHDS2ELC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrEmp2gd3d-ItraMJd6iwu11zRyOMqqpc',
    appId: '1:541360809178:android:a71a7802b6e81a8dfa31e3',
    messagingSenderId: '541360809178',
    projectId: 'contact-app-6f595',
    storageBucket: 'contact-app-6f595.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKRW7JuDmw6VTiPjrLz74kpciVbNr3nx0',
    appId: '1:541360809178:ios:472d945976b76611fa31e3',
    messagingSenderId: '541360809178',
    projectId: 'contact-app-6f595',
    storageBucket: 'contact-app-6f595.appspot.com',
    iosBundleId: 'com.example.exam',
  );
}
